export default {
	CHART_REQUEST_WAITING: "CHART_REQUEST_WAITING",
	CHART_REQUEST_SUCCESS: "CHART_REQUEST_SUCCESS",
	CHART_REQUEST_FAILURE: "CHART_REQUEST_FAILURE",
	CHART_REQUEST_IDLE: "CHART_REQUEST_IDLE",
	CHART_RECEIVED_DATA: "CHART_RECEIVED_DATA"
};
