export default {
	COMPANY_REQUEST_WAITING: "COMPANY_REQUEST_WAITING",
	COMPANY_REQUEST_SUCCESS: "COMPANY_REQUEST_SUCCESS",
	COMPANY_REQUEST_FAILURE: "COMPANY_REQUEST_FAILURE",
	COMPANY_REQUEST_IDLE: "COMPANY_REQUEST_IDLE",
	COMPANY_RECEIVED_DATA: "COMPANY_RECEIVED_DATA"
};
